import { InputProps } from '../../ui/Input/Input';
import { WordList } from '../../libs/bips/bips.d';

export interface MnemonicGroupItemProps extends WordList {
    /**
     * The callback fires when the element's state changes.
     *
     * @param {number} idx Element index.
     * @param {string} val Element value.
     */
    onChange: (idx: number, val: string) => void;
    /**
     * The color of an element.
     * Used for element generated by checksum.
     */
    color?: InputProps['color'];
    /**
     * If 'true', the component is disabled.
     * Used for element generated by checksum.
     */
    disabled?: boolean;
}
