import React from 'react';
import { SvgIconProps } from '@mui/material/SvgIcon';
import AddIcon from '@mui/icons-material/Add';
import ArrowDropDownIcon from '@mui/icons-material/ArrowDropDown';
import ArrowDropUpIcon from '@mui/icons-material/ArrowDropUp';
import Brightness4OutlinedIcon from '@mui/icons-material/Brightness4Outlined';
import CloseIcon from '@mui/icons-material/Close';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import ChevronLeft from '@mui/icons-material/ChevronLeft';
import ChevronRight from '@mui/icons-material/ChevronRight';
import DragIndicatorIcon from '@mui/icons-material/DragIndicator';
import ExtensionIcon from '@mui/icons-material/Extension';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import ExpandLessIcon from '@mui/icons-material/ExpandLess';
import Favorite from '@mui/icons-material/Favorite';
import FavoriteBorder from '@mui/icons-material/FavoriteBorder';
import LaptopMacIcon from '@mui/icons-material/LaptopMac';
import LightModeIcon from '@mui/icons-material/LightMode';
import Menu from '@mui/icons-material/Menu';
import ModeNightIcon from '@mui/icons-material/ModeNight';
import MoreVertIcon from '@mui/icons-material/MoreVert';
import Star from '@mui/icons-material/Star';
import StarBorder from '@mui/icons-material/StarBorder';
import MuiSearchIcon from '@mui/icons-material/Search';
import MuiDashboardIcon from '@mui/icons-material/Dashboard';
import MuiInfoOutlinedIcon from '@mui/icons-material/InfoOutlined';
import QrCode2Icon from '@mui/icons-material/QrCode2';
import VisibilityIcon from '@mui/icons-material/Visibility';
import VisibilityOffIcon from '@mui/icons-material/VisibilityOff';

export const ArrowDownIcon = (props: SvgIconProps) => <ArrowDropDownIcon {...props} />;
export const ArrowUpIcon = (props: SvgIconProps) => <ArrowDropUpIcon {...props} />;
export const ChevronDownIcon = (props: SvgIconProps) => <ExpandMoreIcon {...props} />;
export const ChevronUpIcon = (props: SvgIconProps) => <ExpandLessIcon {...props} />;
export const ChevronLeftIcon = (props: SvgIconProps) => <ChevronLeft {...props} />;
export const ChevronRightIcon = (props: SvgIconProps) => <ChevronRight {...props} />;
export const ComponentIcon = (props: SvgIconProps) => <ExtensionIcon {...props} />;
export const CopyIcon = (props: SvgIconProps) => <ContentCopyIcon {...props} />;
export const CrossIcon = (props: SvgIconProps) => <CloseIcon {...props} />;
export const DashboardIcon = (props: SvgIconProps) => <MuiDashboardIcon {...props} />;
export const DotsVerticalIcon = (props: SvgIconProps) => <MoreVertIcon {...props} />;
export const DragIcon = (props: SvgIconProps) => <DragIndicatorIcon {...props} />;
export const FavoriteIcon = (props: SvgIconProps) => <Favorite {...props} />;
export const FavoriteBorderIcon = (props: SvgIconProps) => <FavoriteBorder {...props} />;
export const InfoOutlinedIcon = (props: SvgIconProps) => <MuiInfoOutlinedIcon {...props} />;
export const ModeLightIcon = (props: SvgIconProps) => <LightModeIcon {...props} />;
export const ModeDarkIcon = (props: SvgIconProps) => <ModeNightIcon {...props} />;
export const MenuIcon = (props: SvgIconProps) => <Menu {...props} />;
export const ModeAutoIcon = (props: SvgIconProps) => <Brightness4OutlinedIcon {...props} />;
export const PCIcon = (props: SvgIconProps) => <LaptopMacIcon {...props} />;
export const PlusIcon = (props: SvgIconProps) => <AddIcon {...props} />;
export const SearchIcon = (props: SvgIconProps) => <MuiSearchIcon {...props} />;
export const ShowOnIcon = (props: SvgIconProps) => <VisibilityIcon {...props} />;
export const ShowOffIcon = (props: SvgIconProps) => <VisibilityOffIcon {...props} />;
export const StarIcon = (props: SvgIconProps) => <Star {...props} />;
export const StarBorderIcon = (props: SvgIconProps) => <StarBorder {...props} />;
export const QrCodeIcon = (props: SvgIconProps) => <QrCode2Icon {...props} />;
