import React from 'react';
import { SvgIconProps } from '@mui/material/SvgIcon';
import AddIcon from '@mui/icons-material/Add';
import ArrowDropDownIcon from '@mui/icons-material/ArrowDropDown';
import ArrowDropUpIcon from '@mui/icons-material/ArrowDropUp';
import ArrowBackIosNewIcon from '@mui/icons-material/ArrowBackIosNew';
import ArrowForwardIosIcon from '@mui/icons-material/ArrowForwardIos';
import Brightness4OutlinedIcon from '@mui/icons-material/Brightness4Outlined';
import CloseIcon from '@mui/icons-material/Close';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import ChevronLeft from '@mui/icons-material/ChevronLeft';
import ChevronRight from '@mui/icons-material/ChevronRight';
import DragIndicatorIcon from '@mui/icons-material/DragIndicator';
import ExtensionIcon from '@mui/icons-material/Extension';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import ExpandLessIcon from '@mui/icons-material/ExpandLess';
import GitHub from '@mui/icons-material/GitHub';
import Favorite from '@mui/icons-material/Favorite';
import FavoriteBorder from '@mui/icons-material/FavoriteBorder';
import LaptopMacIcon from '@mui/icons-material/LaptopMac';
import LightModeIcon from '@mui/icons-material/LightMode';
import Menu from '@mui/icons-material/Menu';
import ModeNightIcon from '@mui/icons-material/ModeNight';
import MoreVertIcon from '@mui/icons-material/MoreVert';
import Star from '@mui/icons-material/Star';
import StarBorder from '@mui/icons-material/StarBorder';
import MuiSearchIcon from '@mui/icons-material/Search';
import MuiDashboardIcon from '@mui/icons-material/Dashboard';
import MuiInfoOutlinedIcon from '@mui/icons-material/InfoOutlined';
import QrCode2Icon from '@mui/icons-material/QrCode2';
import VisibilityIcon from '@mui/icons-material/Visibility';
import VisibilityOffIcon from '@mui/icons-material/VisibilityOff';
import External from './ExternalIcon';
import Brain from './BrainIcon';

export const ArrowDownIcon = (props: SvgIconProps) => <ArrowDropDownIcon data-testid={undefined} {...props} />;
export const ArrowUpIcon = (props: SvgIconProps) => <ArrowDropUpIcon data-testid={undefined} {...props} />;
export const BrainIcon = (props: SvgIconProps) => <Brain {...props} />;
export const ChevronDownIcon = (props: SvgIconProps) => <ExpandMoreIcon data-testid={undefined} {...props} />;
export const ChevronUpIcon = (props: SvgIconProps) => <ExpandLessIcon data-testid={undefined} {...props} />;
export const ChevronLeftIcon = (props: SvgIconProps) => <ChevronLeft data-testid={undefined} {...props} />;
export const ChevronRightIcon = (props: SvgIconProps) => <ChevronRight data-testid={undefined} {...props} />;
export const ChevronLargeLeftIcon = (props: SvgIconProps) => <ArrowBackIosNewIcon data-testid={undefined} {...props} />;
export const ChevronLargeRightIcon = (props: SvgIconProps) => (
    <ArrowForwardIosIcon data-testid={undefined} {...props} />
);
export const ComponentIcon = (props: SvgIconProps) => <ExtensionIcon data-testid={undefined} {...props} />;
export const CopyIcon = (props: SvgIconProps) => <ContentCopyIcon data-testid={undefined} {...props} />;
export const CrossIcon = (props: SvgIconProps) => <CloseIcon data-testid={undefined} {...props} />;
export const DashboardIcon = (props: SvgIconProps) => <MuiDashboardIcon data-testid={undefined} {...props} />;
export const DotsVerticalIcon = (props: SvgIconProps) => <MoreVertIcon data-testid={undefined} {...props} />;
export const DragIcon = (props: SvgIconProps) => <DragIndicatorIcon data-testid={undefined} {...props} />;
export const ExternalIcon = (props: SvgIconProps) => <External {...props} />;
export const FavoriteIcon = (props: SvgIconProps) => <Favorite data-testid={undefined} {...props} />;
export const FavoriteBorderIcon = (props: SvgIconProps) => <FavoriteBorder data-testid={undefined} {...props} />;
export const GitHubIcon = (props: SvgIconProps) => <GitHub data-testid={undefined} {...props} />;
export const InfoOutlinedIcon = (props: SvgIconProps) => <MuiInfoOutlinedIcon data-testid={undefined} {...props} />;
export const ModeLightIcon = (props: SvgIconProps) => <LightModeIcon data-testid={undefined} {...props} />;
export const ModeDarkIcon = (props: SvgIconProps) => <ModeNightIcon data-testid={undefined} {...props} />;
export const MenuIcon = (props: SvgIconProps) => <Menu data-testid={undefined} {...props} />;
export const ModeAutoIcon = (props: SvgIconProps) => <Brightness4OutlinedIcon data-testid={undefined} {...props} />;
export const PCIcon = (props: SvgIconProps) => <LaptopMacIcon data-testid={undefined} {...props} />;
export const PlusIcon = (props: SvgIconProps) => <AddIcon data-testid={undefined} {...props} />;
export const SearchIcon = (props: SvgIconProps) => <MuiSearchIcon data-testid={undefined} {...props} />;
export const ShowOnIcon = (props: SvgIconProps) => <VisibilityIcon data-testid={undefined} {...props} />;
export const ShowOffIcon = (props: SvgIconProps) => <VisibilityOffIcon data-testid={undefined} {...props} />;
export const StarIcon = (props: SvgIconProps) => <Star data-testid={undefined} {...props} />;
export const StarBorderIcon = (props: SvgIconProps) => <StarBorder data-testid={undefined} {...props} />;
export const QrCodeIcon = (props: SvgIconProps) => <QrCode2Icon data-testid={undefined} {...props} />;
